### ISSUE TITLE
Last news color formatting

### ISSUE THREAD

**Issue by flxrin1337** [JohnyCore/nrhelper#1]
you know that you have a 3 minutes cooldown between your own /news's right
you can add a statement to check if your name matches the name that's on /last, and have the timer red-colored if 3 minutes didn't pass
Like this, but make it red because you're still on cooldown cuz that was your /news

![image](https://github.com/user-attachments/assets/7ea6680f-29c5-4385-ae7a-54867542f9a2)

**Comment by JohnyCore** [comment]
# Thank you for the suggestion! ❤️



I've implemented the 3-minute cooldown feature for the `/news` command. Now, if your name matches the last `/news` publisher and 3 minutes haven't passed, the timer will turn red to indicate you're still on cooldown. If the last news was published by someone else, the timer will behave normally and show the usual formatted time.

Here's a breakdown of the changes:
- **Your news, your cooldown:** If you were the last one to publish a `/news`, the timer turns red while you're still within the 3-minute cooldown.
- **Someone else's news:** If the last `/news` wasn't from you, the timer stays formatted with the regular color based on how much time has passed.

This should make the cooldown system clearer and more user-friendly!
Thanks again for your feedback, it was super helpful! 😊

If the last `/news` matches your name:
> ![image](https://github.com/user-attachments/assets/6953d721-1c29-46c3-9d67-fa0e416a3bff)
> ![image](https://github.com/user-attachments/assets/6ed7ff45-1a08-4b1b-8752-53805c8edad6)
![image](https://github.com/user-attachments/assets/141c7611-fc8f-460f-8820-2d5304f39ab0)


If the last `/news` is from someone else:
> ![image](https://github.com/user-attachments/assets/b793e1cf-cf9c-4b44-9a1e-2912d278c133)
> ![image](https://github.com/user-attachments/assets/521ffb3b-cadc-4cd4-bee7-9f23228bcf20)

**Comment by JohnyCore** [comment]
@flxrin1337 **NRHelper** has been updated with the fixes you've suggested.
Thanks for your feedback, which helped me improve the mod even further! ❤️

You can read about the new version here:
[![Release Version](https://img.shields.io/github/v/release/JohnyCore/nrhelper)](https://github.com/JohnyCore/nrhelper/releases/1.0.8)
