### ISSUE TITLE
Change last news announcement on faction chat

### ISSUE THREAD

**Issue by flxrin1337** [JohnyCore/nrhelper#2]
It'd look better and more professional with "N/A" or just a client message, similar to the one you get if you use [/last].

![image](https://github.com/user-attachments/assets/555946cf-56cb-4836-9998-3d60c173e7ee)

**Comment by JohnyCore** [comment]
# Thank you for the suggestion! ❤️

The issue you've mentioned has been fixed. Now, when you use the `/lasf` command and there is no information available about the last news announcement, you'll see a notification indicating that no recent news times are available.

![image](https://github.com/user-attachments/assets/c0d9fdc7-5ff3-4963-b5bf-ce851002da16)

**Comment by JohnyCore** [comment]
@flxrin1337 **NRHelper** has been updated with the fixes you've suggested.
Thanks for your feedback, which helped me improve the mod even further! ❤️

You can read about the new version here:
[![Release Version](https://img.shields.io/github/v/release/JohnyCore/nrhelper)](https://github.com/JohnyCore/nrhelper/releases/1.0.8)
