### ISSUE TITLE
Fix [/ziare] to sell newspapers at the new price - $1000

### ISSUE THREAD

**Issue by flxrin1337** [JohnyCore/nrhelper#3]
As the title says, News Reporters's internal rules have been changed. Now the newspaper is sold at $1000.

**Comment by flxrin1337** [comment]
![image](https://github.com/user-attachments/assets/bb5a7369-4fb7-4a17-8dd8-d1952aec4e2b)

**Comment by JohnyCore** [comment]
@flxrin1337 Hello, Thanks for your feedback! I am aware of the rules, and the mod will be updated in a few minutes. ❤️
