### ISSUE TITLE
Register a comand to put yourself on duty whenever you login.

### ISSUE THREAD

**Issue by flxrin1337** [JohnyCore/nrhelper#4]
The title says it all. Make it toggle-able to be an optional feature, in case that there are users that don't want it turned on. Forgetting that you have to put yourself on duty sucks.

**Comment by JohnyCore** [comment]
Hello,

Thank you for your suggestion! However, I've decided not to implement this feature. Automating tasks such as putting yourself on duty takes away from the manual responsibilities of being a News Reporter. I was a former member and believe these tasks are very crucial to the role. 

Additionally, as a solo developer, such a feature would increase my workload, like having responsibility if something is going wrong, managing any consequences, etc..

I need to prioritize features that I consider more important. I appreciate your understanding in advance!
